dico_mapping = \
{
	'lum':{
		1 : "Plein jour",
		2 : "Crépuscule ou aube",
		3 : "Nuit sans éclairage public",
		4 : "Nuit avec éclairage public non allumé ",
		5 : "Nuit avec éclairage public allumé",
	},
	'agg':{
	1 : "Hors agglomération",
	2 : "En agglomération",
	},
	'int':{
	1 : "Hors intersection",
	2 : "Intersection en X",
	3 : "Intersection en T",
	4 : "Intersection en Y",
	5 : "Intersection à plus de 4 branches",
	6 : "Giratoire",
	7 : "Place",
	8 : "Passage à niveau ",
	9 : "Autre intersection",
	},
	'atm':{
	1 : "Normale",
	2 : "Pluie légère",
	3 : "Pluie forte",
	4 : "Neige - grêle",
	5 : "Brouillard - fumée ",
	6 : "Vent fort - tempête ",
	7 : "Temps éblouissant ",
	8 : "Temps couvert",
	9 : "Autre",
	},
	'mois':{
	1  : "Janvier",
	2  : "Février",
	3  : "Mars",
	4  : "Avril",
	5  : "Mai",
	6  : "Juin",
	7  : "Juillet",
	8  : "Août",
	9  : "Septembre",
	10 : "Octobre",
	11 : "Novembre",
	12 : "Décembre",
	},
	'surf':{
	1 : "normale",
	2 : "mouillée",
	3 : "flaques",
	4 : "inondée",
	5 : "enneigée",
	6 : "boue",
	7 : "verglacée",
	8 : "corps gras - huile ",
	9 : "autre",
	},
	'catv':{
	 1 : "Bicyclette",
	 2 : "Cyclomoteur <50cm3",
	 3 : "Voiturette",
	 4 : "Scooter immatriculé",
	 5 : "Motocyclette",
	 6 : "Side-car",
	 7 : "Véhicule Léger seul",
	 8 : "VL + caravane",
	 9 : "VL + remorque",
	10 : "VU seul 1,5T <= PTAC <= 3,5T",
	11 : "Caravane",
	12 : "Remorque",
	13 : "PL seul 3,5T <PTCA <= 7,5T",
	14 : "PL seul > 7,5T",
	15 : "PL > 3,5T + remorque",
	16 : "Tracteur routier seul",
	17 : "Tracteur routier + semi-remorque",
	18 : "Transport en commun",
	19 : "Tramway",
	20 : "Engin spécial",
	21 : "Tracteur agricole",
	30 : "Scooter < 50 cm3",
	31 : "Motocyclette > 50 cm3 a <= 125 cm3",
	32 : "Scooter >50cm3 et <=125cm3",
	33 : "Motocyclette > 125 cm3",
	34 : "Scooter > 125 :cm3",
	35 : "Quad léger <= 50 cm3",
	36 : "Quad lourd > 50 cm3",
	37 : "Autobus",
	38 : "Autocar",
	39 : "Train",
	40 : "Tramway",
	99 : "Autre véhicule",
	},
	'catu':{
	1 : "Conducteur",
	2 : "Passager",
	3 : "Piéton",
	4 : "Piéton en roller ou en trottinette",
	},
	'grav':{
	1 : "Indemne",
	2 : "Tué",
	3 : "Blessé hospitalisé ",
	4 : "Blessé léger",
	},
	'sexe':{
	1 : "Masculin",
	2 : "Féminin",
	},
	'trajet':{
	1 : "Domicile – travail",
	2 : "Domicile – école",
	3 : "Courses – achats",
	4 : "Utilisation professionnelle ",
	5 : "Promenade – loisirs",
	9 : "Autre",
	},
	'catr':{
	1 : "Autoroute",
	2 : "Route nationale",
	3 : "Route départementale",
	4 : "Voie communale",
	5 : "Hors réseau public",
	6 : "Parc de stationnement ouvert à la circulation publique",
	7 : "Routes de métropole urbaine",
	9 : "Autre",
	},
	'dep':{
	'01' : "Ain",
	'02' : "Aisne",
	'03' : "Allier",
	'04' : "Alpes-de-Haute-Provence",
	'05' : "Hautes-Alpes",
	'06' : "Alpes-Maritimes",
	'07' : "Ardèche",
	'08' : "Ardennes",
	'09' : "Ariège",
	'10': "Aube",
	'11' : "Aude",
	'12' : "Aveyron",
	'13' : "Bouches-du-Rhône",
	'14' : "Calvados",
	'15' : "Cantal",
	'16' : "Charente",
	'17' : "Charente-Maritime",
	'18' : "Cher",
	'19' : "Corrèze",
	'2A' : "Corse-du-Sud",
	'2B' : "Haute-Corse",
	'21' : "Côte-d'Or",
	'22' : "Côtes-d'Armor",
	'23' : "Creuse",
	'24' : "Dordogne",
	'25' : "Doubs",
	'26' : "Drôme",
	'27' : "Eure",
	'28' : "Eure-et-Loir",
	'29' : "Finistère",
	'30' : "Gard",
	'31' : "Haute-Garonne",
	'32' : "Gers",
	'33' : "Gironde",
	'34' : "Hérault",
	'35' : "Ille-et-Vilaine",
	'36' : "Indre",
	'37' : "Indre-et-Loire",
	'38' : "Isère",
	'39' : "Jura",
	'40' : "Landes",
	'41' : "Loir-et-Cher",
	'42' : "Loire",
	'43' : "Haute-Loire",
	'44' : "Loire-Atlantique",
	'45' : "Loiret",
	'46' : "Lot",
	'47' : "Lot-et-Garonne",
	'48' : "Lozère",
	'49' : "Maine-et-Loire",
	'50' : "Manche",
	'51' : "Marne",
	'52' : "Haute-Marne",
	'53' : "Mayenne",
	'54' : "Meurthe-et-Moselle",
	'55' : "Meuse",
	'56' : "Morbihan",
	'57' : "Moselle",
	'58' : "Nièvre",
	'59' : "Nord",
	'60' : "Oise",
	'61' : "Orne",
	'62' : "Pas-de-Calais",
	'63' : "Puy-de-Dôme",
	'64' : "Pyrénées-Atlantiques",
	'65' : "Hautes-Pyrénées",
	'66' : "Pyrénées-Orientales",
	'67' : "Bas-Rhin",
	'68' : "Haut-Rhin",
	'69' : "Rhône",
	'70' : "Haute-Saône",
	'71' : "Saône-et-Loire",
	'72' : "Sarthe",
	'73' : "Savoie",
	'74' : "Haute-Savoie",
	'75' : "Paris",
	'76' : "Seine-Maritime",
	'77' : "Seine-et-Marne",
	'78' : "Yvelines",
	'79' : "Deux-Sèvres",
	'80' : "Somme",
	'81' : "Tarn",
	'82' : "Tarn-et-Garonne",
	'83' : "Var",
	'84' : "Vaucluse",
	'85' : "Vendée",
	'86' : "Vienne",
	'87' : "Haute-Vienne",
	'88' : "Vosges",
	'89' : "Yonne",
	'90' : "Territoire de Belfort",
	'91' : "Essonne",
	'92' : "Hauts-de-Seine",
	'93' : "Seine-Saint-Denis",
	'94' : "Val-de-Marne",
	'95' : "Val-d'Oise",
	'971' : "Guadeloupe",
	'972' : "Martinique",
	'973' : "Guyane",
	'974' : "La Réunion",
	'976' : "Mayotte",	
	}
}
